services:
  nakama:
    build: .
    env_file:
      - .env
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up
        --database.address "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
        &&
        /nakama/nakama --config /nakama/data/local.yml
        --database.address "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
        --socket.server_key "${SOCKET_SERVER_KEY}"
        --session.encryption_key "${SESSION_ENCRYPTION_KEY}"
    volumes:
      - ./local.yml:/nakama/data/local.yml
    ports:
      - "7349:7349" # gRPC
      - "7350:7350" # HTTP/WebSocket API
      - "7351:7351" # Dashboard (Developer Console)
    restart: always
