name: "nakama-tictactoe"
database:
  address:
    - "root@cockroachdb:26257"
  region: "local"

runtime:
  env:
    - "DEBUG=true"

logger:
  level: "info"
  format: "json"

session:
  encryption_key: "defaultkey" # CHANGE THIS IN PRODUCTION
  token_expiry_sec: 3600

socket:
  server_key: "defaultkey" # CHANGE THIS IN PRODUCTION
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "password" # dashboard login
