name: "nakama-tictactoe"

database:
  address: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

runtime:
  env:
    - "DEBUG=true"

logger:
  level: "info"
  format: "json"

session:
  encryption_key: "${SESSION_ENCRYPTION_KEY}"
  token_expiry_sec: 3600

socket:
  server_key: "${SOCKET_SERVER_KEY}"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "password" # dashboard login
